add functionality for streaming and decimate files from grane (.sgd)
equinor/seis-ee pull request #12
Opened 2021-02-02 08:46 UTC by KristianKjerstad

Note: the changes use the Equinor python library segdpy, which must be locally installed.

2021-02-02 08:49 UTC, KristianKjerstad commented
Are there any simple ways to include the [segdpy package](https://github.com/equinor/segdpy/tree/master/segdpy) with docker?

2021-02-04 07:50 UTC, soofstad requested changes
Nice job. Looks good :)

2021-02-04 07:50 UTC, soofstad commented on seis_ee/find_files/grane.py
>      # Try splitting the filename
Possible to reuse this function in the one below?

2021-02-04 07:50 UTC, soofstad commented on seis_ee/find_files/oseberg.py
> +        if (path != None and file_time != None ):
Not sure we want this.
We want to be able to see when there are missing files in a time period

2021-02-04 10:15 UTC, merged